CREATE TABLE Loja (
  idLoja INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NULL,
  PRIMARY KEY(idLoja)
);

CREATE TABLE Console (
  idConsole INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descritivo VARCHAR(100) NULL,
  PRIMARY KEY(idConsole)
);

CREATE TABLE Game (
  idGame INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idConsole INTEGER UNSIGNED NOT NULL,
  nome VARCHAR(100) NULL,
  PRIMARY KEY(idGame),
  INDEX Game_FKIndex1(idConsole),
  FOREIGN KEY(idConsole)
    REFERENCES Console(idConsole)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Game_Loja (
  idGame_Loja INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idLoja INTEGER UNSIGNED NOT NULL,
  idGame INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idGame_Loja),
  INDEX Game_Loja_FKIndex1(idGame),
  INDEX Game_Loja_FKIndex2(idLoja),
  FOREIGN KEY(idGame)
    REFERENCES Game(idGame)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idLoja)
    REFERENCES Loja(idLoja)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


